- hosts: k8s_masters[0]
  become: yes
  roles:
    - cfssl
    - kubectl
    - ca-gen
    - encryption-config-gen
    - admin-kubeconfig-gen
    - controlplane-kubeconfigs-gen
    - fetch-controlplane-configs

- hosts: k8s_masters
  become: yes
  roles:
    - cfssl
    - kubectl
    - copy-controlplane-configs
    - etcd-bootstrap