- hosts: k8s_masters[0]
  become: yes
  roles:
    - cfssl
    - kubectl
    - ca-gen
    - encryption-config-gen
    - admin-kubeconfig-gen
    - fetch-ca-certs

- hosts: k8s_masters
  become: yes
  roles:
    - cfssl
    - kubectl
    - copy-ca-certs
    - admin-kubeconfig-gen
    - controlplane-kubeconfigs-gen
    - etcd-bootstrap