- hosts: k8s_masters[0]
  become: yes
  roles:
    - cfssl
    - kubectl
    - ca-gen
    - encryption-config-gen
    - admin-kubeconfig-gen
    - controlplane-kubeconfigs-gen
    - etcd-certs-gen
    - fetch-controlplane-configs

- hosts: k8s_masters
  become: yes
  roles:
    - etc-hosts-config
    - copy-controlplane-configs
    - etcd-bootstrap
    - controlplane-bootstrap
    - python-packages
    - kubectl

- hosts: k8s_workers
  become: yes
  roles:
    - etc-hosts-config
    - cfssl
    - crictl
    - runc
    - cni-plugins
    - containerd
    - worker-kubeconfigs-gen
    - worker-bootstrap
    - kubectl
 
- hosts: k8s_masters[0]
  become: yes
  gather_facts: no
  tasks:
    - name: Install RBAC for kubelet
      include_role:
        name: rbac-for-kubelet

    - name: Install CoreDNS
      include_role:
        name: coredns

# Doesn't work yet
    - name: Install Metrics-server
      include_role:
        name: metrics-server

    - name: Install Ingress Controller
      include_role:
        name: "{{ ingress_controller }}_ingress_controller"
      when: install_ingress_controller | bool

    - name: Install LoadBalancer
      include_role:
        name: "{{ loadbalancer }}_loadbalancer"
      when: install_loadbalancer | bool

    - name: Install CNI
      include_role:
        name: "{{ cni }}"
