- hosts: k8s_masters[0]
  become: yes
  roles:
    - cfssl
    - kubectl
    - ca-gen
    - encryption-config-gen
    - admin-kubeconfig-gen
    - controlplane-kubeconfigs-gen
    - etcd-certs-gen
    - fetch-controlplane-configs

- hosts: k8s_masters
  become: yes
  roles:
    - etc-hosts-config
    - copy-controlplane-configs
    - etcd-bootstrap
    - controlplane-bootstrap
    - python-packages
    - kubectl

- hosts: k8s_workers
  become: yes
  roles:
    - etc-hosts-config
    - cfssl
    - crictl
    - kubectl
    - runc
    - cni-plugins
    - containerd
    - worker-kubeconfigs-gen
    - worker-bootstrap
 
- hosts: k8s_masters[0]
  become: yes
  gather_facts: no
  roles:
    # - flannel
    - rbac-for-kubelet
    - coredns
    - calico
    - "{{ ingress_controller }}_ingress_controller"
