- hosts: k8s_masters[0]
  become: yes
  roles:
    - cfssl
    - kubectl
    - ca-gen
    - encryption-config-gen
    - admin-kubeconfig-gen
    - controlplane-kubeconfigs-gen
    - etcd-certs-gen
    - fetch-controlplane-configs

- hosts: k8s_masters
  become: yes
  roles:
    - python-packages
    - kubectl
    - copy-controlplane-configs
    - etcd-bootstrap
    - controlplane-bootstrap

- hosts: k8s_masters[0]
  become: yes
  gather_facts: no
  roles:
    - rbac-for-kubelet

- hosts: k8s_workers
  become: yes
  roles:
    - cfssl
    - crictl
    - kubectl
    - runc
    - containerd
    - worker-kubeconfigs-gen
    - worker-bootstrap
 
- hosts: k8s_masters[0]
  become: yes
  gather_facts: no
  roles:
    - flannel
    - coredns
