- name: Create /var/lib/kubernetes dir
  file:
    path: /var/lib/kubernetes
    state: directory

- name: Copy CA cert to master nodes
  copy:
    src: "{{ k8s_local_temp_dir }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  loop:
    - ca.pem
    - ca-key.pem
    - ca-config.json
    - encryption-config.yaml