- name: Check encryption-config.yaml state
  stat:
    path: /var/lib/kubernetes/encryption-config.yaml 
  register: encryption_config_file

- name: Generate encryption key
  shell: "head -c 32 /dev/urandom | base64"
  register: encryption_key
  when: not encryption_config_file.stat.exists

- name: Copy encryption-config.yaml
  template:
    src: encryption-config.yaml.j2
    dest: /var/lib/kubernetes/encryption-config.yaml
  when: not encryption_config_file.stat.exists