- name: Download flannel manifest
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /var/lib/kubernetes/flannel.yml

- name: Apply flannel manifest to the cluster.
  k8s:
    src: /var/lib/kubernetes/flannel.yml
    state: present