- name: Copy flannel manifest
  template:
    src: flannel.yaml.j2
    dest: /var/lib/kubernetes/flannel.yaml

- name: Apply flannel manifest to the cluster.
  k8s:
    src: /var/lib/kubernetes/flannel.yaml
    state: present