---
- name: Download Nginx ingress controller manifest
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ nginx_ingress_version }}/deploy/static/provider/{{ nginx_ingress_provider }}/deploy.yaml"
    dest: /tmp/nginx_ingress_controller.yaml

- name: Apply Nginx ingress controller manifest
  community.kubernetes.k8s:
    state: present
    src: /tmp/nginx_ingress_controller.yaml
