- name: Copy CoreDNS manifest
  copy:
    src: coredns.yaml
    dest: /var/lib/kubernetes/coredns.yaml

- name: Apply coredns manifest to the cluster.
  k8s:
    src: /var/lib/kubernetes/coredns.yaml
    state: present