- name: Download coredns manifest
  get_url:
    url: "https://storage.googleapis.com/kubernetes-the-hard-way/coredns-{{ coredns_version }}.yaml"
    dest: /var/lib/kubernetes/coredns.yaml

- name: Apply coredns manifest to the cluster.
  k8s:
    src: /var/lib/kubernetes/coredns.yaml
    state: present