- name: Create /etc/kubernetes/pki dir
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: Copy CA configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kubernetes/pki/{{ item }}"
  loop:
    - admin-csr.json

- name: Generate admin cert and key
  shell:
    cmd: >
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem
      -config=ca-config.json -profile=kubernetes 
      admin-csr.json | cfssljson -bare admin
    chdir: /etc/kubernetes/pki
    creates: /etc/kubernetes/pki/admin.pem