- name: Create /var/lib/kubernetes dir
  file:
    path: /var/lib/kubernetes
    state: directory

- name: Copy CA configs
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/kubernetes/{{ item }}"
  loop:
    - ca-config.json
    - ca-csr.json

- name: Generate CA cert and key
  shell:
    cmd: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
    chdir: /var/lib/kubernetes
    creates: /var/lib/kubernetes/ca.pem