---

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install pip
  yum:
    name: python3-pip
  when: ansible_os_family == 'RedHat'

- name: Install pip packages
  pip:
    name: "{{ item }}"
  loop:
    - kubernetes==11
    - openshift==0.11