- name: Create /var/lib/kubernetes dir
  file:
    path: /var/lib/kubernetes
    state: directory

- name: Copy kube-proxy CSR config
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/kubernetes/{{ item }}"
  loop:
    - kube-proxy-csr.json

- name: Copy kubelet CSR config
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/kubernetes/{{ ansible_hostname }}-csr.json"
  loop:
    - kubelet-csr.json

- name: Generate kube-proxy cert and key
  shell:
    cmd: >
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem
      -config=ca-config.json -profile=kubernetes
      kube-proxy-csr.json | cfssljson -bare kube-proxy
    chdir: /var/lib/kubernetes
    creates: /var/lib/kubernetes/kube-proxy.pem

- name: Generate kubelet cert and key
  shell:
    cmd: >
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json 
      -hostname={{ ansible_hostname }},{{ ansible_default_ipv4.address }} -profile=kubernetes
      {{ ansible_hostname }}-csr.json | cfssljson -bare {{ ansible_hostname }}
    chdir: /var/lib/kubernetes
    creates: "/var/lib/kubernetes/{{ ansible_hostname }}.pem"